---
source: _sv
destination: ''
source_stylesheet: application.scss
source_javascript: application.js
destination_stylesheet: _sv_custom.css
destination_javascript: _sv_custom.js
layout: _layout.liquid
includes: _includes
compile_sprite: false
compile_js: false
